[package]
name = "Cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
scraper = "0.20.0"
serde_json = "1.0.122"
serde = "1.0.204"